# This is a basic workflow to help you get started with Actions

name: generate_stats

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Merge the stats with prefix & postfix string
        run: |
          stats=$(curl -X GET "https://shitdev.nl/api/wakatime_text?username=notselwyn&editors=0")
          echo -e "\`\`\`console\n\$ stats\n${stats}\n\`\`\`" > STATS.md
      - name: Compile the README.md file
        run: |
          c_neofetch=$(cat NEOFETCH.md)
          c_stats=$(cat STATS.md)
          c_readme="${c_neofetch}\n${c_stats}\n![](https://komarev.com/ghpvc/?username=Notselwyn)]"
          echo -e $c_readme
          echo -e $c_readme > README.md
          
      - name: Commit & Push changes
        run: |
          git add STATS.md
          git config --global user.name 'Auto'
          git config --global user.email 'auto@example.com'
          git commit -am 'Automatic update' || true
          git push
