# This is a basic workflow to help you get started with Actions

name: generate_stats

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
  - cron: "0 */6 * * *"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Merge the text stats with prefix & postfix string
        run: |
          stats=$(curl -X GET "https://shitdev.nl/api/wakatime/circle?username=notselwyn")
          echo -e "\`\`\`console\n\$ stats \n${stats/\\/\\\\}\n\`\`\`" > STATS_CIRCLE.md
      - name: Merge the circle stats with prefix & postfix string
        run: |
          stats=$(curl -X GET "https://shitdev.nl/api/wakatime/text?username=notselwyn&editors=6&languages=6&total_time=true")
          echo -e "\`\`\`console\n\$ stats\n${stats}\n\`\`\`" > STATS_TEXT.md
      - name: Compile the README.md file
        run: |
          cat NEOFETCH.md STATS_CIRCLE.md > README.md
          echo -e "\n![profile counter](https://komarev.com/ghpvc/?username=Notselwyn)" >> README.md
          
      - name: Commit & Push changes
        run: |
          git add STATS_TEXT.md
          git add STATS_CIRCLE.md
          git config --global user.name 'Auto'
          git config --global user.email 'auto@example.com'
          git commit -am 'Automatic update' || true
          git push
